### ISSUE TITLE
the projects Readme's are outdated

### ISSUE THREAD

**Issue by bam80** [koshev-msk/modemfeed#1]
That seem happened when the repos have moved, and projects readme's inside got stale.

So e.g. for https://github.com/koshev-msk/modemfeed/tree/master/luci/applications/luci-app-modeminfo#readme:
- wrong paths to the repo
- no screenshot
- ...

**Comment by koshev-msk** [comment]
Fixed in 74614b5f0acee8d9db73ceb2a85fed1f870214ed

**Comment by bam80** [comment]
https://github.com/koshev-msk/modemfeed/commit/74614b5f0acee8d9db73ceb2a85fed1f870214ed is a fix for `luci-app-smstools3` only, and not other projects here including the main Readme?
