### ISSUE TITLE
/etc/atcommands.user overridden on each reinstall

### ISSUE THREAD

**Issue by bam80** [koshev-msk/modemfeed#12]
https://github.com/4IceG/luci-app-atinout-mod/issues/16

**Comment by koshev-msk** [comment]
Fixed in https://github.com/koshev-msk/modemfeed/commit/e518e625ba27b93f4ed9347e10210489ce2c8239

**Comment by bam80** [comment]
Thank you for a quick fix! If you could share your custom `atcommands.user`, that would be welcomed as I lost mine)
