### ISSUE TITLE
Fibocom FM350 support

### ISSUE THREAD

**Issue by lrdrdn** [koshev-msk/modemfeed#15]
Can you add support for connecting modem Fibocom FM350-GL like xmm-modem?
I successfully connected the modem using [this metode.](https://tylk.cc/fm350-gl%E6%A8%A1%E5%9D%97%E9%80%9A%E8%BF%87usb-rndis%E8%BF%9E%E6%8E%A5%E7%BD%91%E7%BB%9C%E6%8B%A8%E5%8F%B7%E6%96%B9%E6%B3%95/) 

For openwrt using rndis_host.
send this at command:
```
AT+CGDCONT=1,"IPV4V6","internet",,0,0,0,0,0,0,0

AT+CGACT=1,1

AT+CGPADDR=1
```

response CGPADDR
```

AT+CGPADDR=1
+CGPADDR: 1,"10.5.147.243",""
```

and create interface static address eth1 with those address, ipv4 `10.5.147.243`, gateway `10.5.147.1`, and dns `8.8.8.8`

[fibocom_fm350_at_commands_v2.2.pdf](https://github.com/koshev-msk/modemfeed/files/12475142/fibocom_fm350_at_commands_v2.2.pdf)
[FM350GL_Driver.zip](https://github.com/koshev-msk/modemfeed/files/12475150/FM350GL_Driver.zip)

**Comment by mdsdtech** [comment]
Can you share the link where did you buy the modules?. Thank you.

**Comment by lrdrdn** [comment]
> Can you share the link where did you buy the modules?. Thank you.

https://a.aliexpress.com/_mrkAtxw

**Comment by koshev-msk** [comment]
Added inital support in commit https://github.com/koshev-msk/modemfeed/commit/4d12b758e69cf3e20c312ea5d6a5984a958e46d7
