### ISSUE TITLE
modeminfo/Makefile incorrect module name

### ISSUE THREAD

**Issue by Harwesta** [koshev-msk/modemfeed#20]
Incorrect module name line 100: instead
`$(eval $(call SerialPlugin,meig,+kmod-usb-option,MEIGLink SLM750-R2/SLM820/SLM828,MEIGLINK))`
there should be
`$(eval $(call SerialPlugin,meig,+kmod-usb-serial-option,MEIGLink SLM750-R2/SLM820/SLM828,MEIGLINK))`

(I think there is no need to create a pull request)

**Comment by koshev-msk** [comment]
Thnx, fixed in https://github.com/koshev-msk/modemfeed/commit/6cce57c3e0df0b9138a0705962bd00128f4d7c7b
