### ISSUE TITLE
Openwrt 23.05.3 dependency

### ISSUE THREAD

**Issue by lynxnexy** [koshev-msk/modemfeed#38]
WARNING: Makefile 'package/modemfeed/packages/net/3proxy/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/modemfeed/packages/net/accel-ppp/Makefile' has a dependency on 'libpcre', which does not exist
WARNING: Makefile 'package/feeds/telephony/freeswitch/Makefile' has a dependency on 'libpcre', which does not exist

libpcre is not available in openwrt 23.05.3 what is available is libpcre2 can it be replaced with libpcre2 dependency

**Comment by Mig72-jpg** [comment]
Мне нужно сделать поддержку GOBI (SIM7100C) USB 4G LTE модема , на OpenWrt 18.06.2. (Платформа ar71хх (Proc AR9331)  Хотел узнать, как Вы решили проблему сборки ? (has a dependency on 'libxml2', which does not exist). Старшую версию поставить не могу, из-за того что тогда не определяется USB порт ( Там уже ATH79, а в ней вшитый AR7100 и AR7200) и ECHI выдает ошибку...так как этого на железе нет).  Дрова на сайте есть.. но собрать мозгов нет, поэтому хотел использовать modemfeed.  КАК собрать пакеты под 18.06.2 ??
