### ISSUE TITLE
Have problem with ndpi-netfilter compile

### ISSUE THREAD

**Issue by GenzPN** [koshev-msk/modemfeed#6]
[build.log](https://github.com/koshev-msk/modemfeed/files/9895040/build.log)
Run on x-wrt have problem 
![image](https://user-images.githubusercontent.com/39546317/198861712-ad257829-5a58-48eb-ad87-aed79a94beea.png)

**Comment by koshev-msk** [comment]
Try this commit https://github.com/koshev-msk/modemfeed/commit/eb30c9f7e0ccf43614e2b4c1df8ed30ef8f2559f
