### ISSUE TITLE
Modeminfo: temperature missing with Dell DW5829e after FW upgrade 

### ISSUE THREAD

**Issue by Harwesta** [koshev-msk/modemfeed#7]
Hi!

OpenWrt 22.03.2 r19803-9a599fee93 compiled with latest version modemfeed.
Dell DW5829e in MBIM+ports mode (Customer=7, VID=413c, PID=81e6).

After upgrade to firmware T77W968.F2.0.0.1.0.GC.002 1 [May 31 2021 08:00:00] (NYH2V 1.0.0.24_A09_01) temperature is missing on modeminfo page.
But reading with AT-Command "AT^TEMP?" normally response:
```
PA: 31C
TSENS: 35C
OK
```
![temp_bug](https://user-images.githubusercontent.com/65107625/212285928-e229e31c-b890-4bd7-9c4c-4d667587eb36.jpg)

**Comment by koshev-msk** [comment]
Thanks. Fixed in https://github.com/koshev-msk/modemfeed/commit/b9c537171550505d3256167791b80a5bdb5d2e69 .
