### ISSUE TITLE
Update modeminfo Makefile like Passwall or SSR Plus switch

### ISSUE THREAD

**Issue by helmiau** [koshev-msk/modemfeed#8]
Hello, can you add switch (define y or n) like [luci-app-passwall Makefile](https://github.com/immortalwrt/luci/blob/openwrt-21.02/applications/luci-app-passwall/Makefile) or [luci-app-ssr-plus Makefilel](https://github.com/immortalwrt/luci/blob/openwrt-21.02/applications/luci-app-ssr/Makefile) on this [modeminfo Makefile](https://github.com/koshev-msk/modemfeed/blob/master/packages/net/modeminfo/Makefile). This will make modeminfo more configurable before build. Thanks!.

**Comment by koshev-msk** [comment]
Fixed in https://github.com/koshev-msk/modemfeed/commit/f693d995722c50fc97abb690c5826d8084dce906
